# Generated by Django 5.2.4 on 2025-08-06 22:04

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='statics/images/products')),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeofproduct', to='shopApp.producttype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
